import fs from 'fs';
import path from 'path';
import HtmlWebpackPlugin from 'html-webpack-plugin';

function templateContent() {
  return fs.readFileSync(
    path.resolve(process.cwd(), 'src/index.html'),
  ).toString();
}

function indexHtml() {
  return {
    plugins: [
      new HtmlWebpackPlugin({
        inject: true, // Inject all files generated by webpack,
        templateContent: templateContent(),
      }),
    ],
  };
}

export default indexHtml;
